add wave \
{sim:/cpu_tb/uut/clk } \
{sim:/cpu_tb/uut/rst } \
{sim:/cpu_tb/uut/p1x } \
{sim:/cpu_tb/uut/p1y } \
{sim:/cpu_tb/uut/p2x } \
{sim:/cpu_tb/uut/p2y } \
{sim:/cpu_tb/uut/pm } \
{sim:/cpu_tb/uut/upm } \
{sim:/cpu_tb/uut/buss } \
{sim:/cpu_tb/uut/upm_alu } \
{sim:/cpu_tb/uut/upm_tb } \
{sim:/cpu_tb/uut/upm_fb } \
{sim:/cpu_tb/uut/upm_s } \
{sim:/cpu_tb/uut/upm_p } \
{sim:/cpu_tb/uut/upm_lc } \
{sim:/cpu_tb/uut/upm_seq } \
{sim:/cpu_tb/uut/upm_uaddr } \
{sim:/cpu_tb/uut/ir_addr } \
{sim:/cpu_tb/uut/ir_m } \
{sim:/cpu_tb/uut/ir_grx } \
{sim:/cpu_tb/uut/ir_op } \
{sim:/cpu_tb/uut/pc } \
{sim:/cpu_tb/uut/asr } \
{sim:/cpu_tb/uut/grx } \
{sim:/cpu_tb/uut/grx_x } \
{sim:/cpu_tb/uut/ar } \
{sim:/cpu_tb/uut/upc } \
{sim:/cpu_tb/uut/lc } \
{sim:/cpu_tb/uut/z } \
{sim:/cpu_tb/uut/o } \
{sim:/cpu_tb/uut/n } \
{sim:/cpu_tb/uut/c } \
{sim:/cpu_tb/uut/l } 
run 100000000
